# Generated by Django 4.2.5 on 2024-01-27 08:09

from django.db import migrations, models
import django.db.models.deletion
import storeroom.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('device_status', models.CharField(max_length=50)),
                ('device_brand', models.CharField(max_length=50)),
                ('device_mileage', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('image_5', models.ImageField(upload_to='')),
                ('image_6', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=50, validators=[storeroom.validators.persian_valid])),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[(1, 'entry'), (2, 'Temporary exit'), (3, 'permanent exit')], default=1, max_length=1)),
                ('time', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeroom.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeroom.project'),
        ),
    ]
